# Generated by Django 5.2 on 2025-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category_images/news_cat.jpg', null=True, upload_to='category_images/'),
        ),
    ]
